# Build image
FROM rust:slim-buster AS build

RUN apt update && apt install -y libssl-dev pkg-config && rm -rf /var/lib/apt

WORKDIR /root/rsm

COPY Cargo.toml Cargo.lock ./
COPY src ./src

RUN cargo build --release

# Runtime image
FROM debian:buster-slim

RUN apt update && apt install -y libssl-dev iputils-ping  && rm -rf /var/lib/apt

COPY --from=build /root/rsm/target/release/rsm /usr/bin/rsm
COPY tests/ressources/example.yaml /etc/rsm.yaml

CMD ["/bin/bash"]


